name: Build Test
on:
  push:
    branches:
    - 'ros2'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    runs-on: [self-hosted, linux]
    strategy:
      fail-fast: false
      matrix:
        config:
          - {rosdistro: 'humble', container: 'osrf/ros:humble-desktop'}
    container: ${{ matrix.config.container }}
    steps:
    - uses: actions/checkout@v1
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install Dependencies
      working-directory: 
      run: |
        apt update
        apt install -y python3-wstool libgdal-dev ros-${{matrix.config.rosdistro}}-tf2-geometry-msgs
      shell: bash
    - name: Build Test
      working-directory: 
      run: |
        mkdir -p $HOME/ros2_ws/src;
        cd $HOME/ros2_ws/src
        ln -s $GITHUB_WORKSPACE
        cd $HOME/ros2_ws
        source /opt/ros/humble/setup.bash
        wstool init src src/terrain-navigation/dependencies.rosinstall
        wstool update -t src -j4
        rosdep update
        rosdep install --from-paths src --ignore-src -y --rosdistro ${{matrix.config.rosdistro}}
        colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release --packages-up-to terrain_navigation_ros
      shell: bash
    - name: unit_tests
      working-directory:
      run: |
        cd $HOME/catkin_ws/src
        catkin config --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCATKIN_ENABLE_TESTING=True
        catkin build terrain_planner --no-deps -i --catkin-make-args tests
        source $HOME/catkin_ws/devel/setup.bash
        status=0 && for f in $HOME/catkin_ws/devel/lib/*/*-test; do $f || exit 1; done
      shell: bash
